- name: COPY | dotfiles for root
  copy:
    src: "{{ item }}"
    dest: "/home/vagrant/.{{ item }}"
  with_items:
    - "bash_aliases"
    - "screenrc"
    - "gitconfig"

- name: Install some apps
  apt:
    pkg:
    - git
    - terminator
    - unzip

- name: Install ZSH
  shell: curl https://raw.githubusercontent.com/viasite-ansible/ansible-role-zsh/master/install.sh | bash
  args:
    warn: no
