- name: Ensure ES locale in inserted into locale.gen
  locale_gen:
    name: es_MX.UTF-8
    state: present

- name: Ensure EN locale in inserted into locale.gen
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Ensure LANG is set in environment file
  lineinfile:
    name: /etc/environment
    regexp: '^LANG="es_MX.UTF-8"$'
    line: 'LANG="es_MX.UTF-8"'

- name: Reload locales
  shell: "dpkg-reconfigure -f noninteractive locales"
  environment:
   - LANG: "es_MX.UTF-8"